name: Test Flask App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        python -c 'import nltk; nltk. download(["punkt", "stopwords","wordnet"])'
    - name: Run Tests
      run: |
        python -m unittest discover -p "*_test.py"
    - name: Analysing the code with pylint
      run: |
        pylint -d R0903,W0702,R0913,R0903,R1732 $(git ls-files '*.py')
